import { PropsWithChildren } from 'react';
import '../src/styles/globals.css';
import Providers from '@/utils/provider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function Layout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <main className="h-screen w-full bg-primary">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
